server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-service-registry

eureka:
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:localhost}
    non-secure-port: ${PORT:8761}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
