server:
  port: ${EUREKA_PORT:8761}

spring:
  application:
    name: ms-service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:eureka}
    prefer-ip-address: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
