<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.finanzas</groupId>
        <artifactId>gestor-finanzas-backend</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>architecture</artifactId>
    <packaging>pom</packaging>
    <name>Architecture Services</name>
    <description>Servicios de arquitectura e infraestructura (Eureka, Gateway, Config Server)</description>

    <modules>
        <module>ms-service-registry</module>
        <module>ms-api-gateway</module>
        <module>ms-config-server</module>
    </modules>

</project>
