server:
  port: 8765

spring:
  application:
    name: ms-service-registry

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8765
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8765/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,refresh
  endpoint:
    health:
      show-details: always
