server:
  port: 8765

spring:
  application:
    name: ms-service-registry

eureka:
  instance:
    hostname: ${HOSTNAME}
    non-secure-port: 8765
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://qa-eureka:8765/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
