# Configuración local de fallback (solo se usa si config-server no está disponible)
server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: ms-api-gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.finanzas.apigateway: INFO
    org.springframework.cloud.config: INFO
